export type AuditAction =
  | "SUBMISSION_UPSERT"
  | "SUBMISSION_DELETE"
  | "FILE_UPLOAD"
  | "FILE_RENAME"
  | "FILE_DELETE"
  | "VERIFY_UPDATE"
  | "TEACHER_APPROVE"
  | "TEACHER_DEACTIVATE"
  | "REMINDER_SENT"
  | "EXPORT_PDF"
  | "EXPORT_EXCEL"
  | "EXPORT_CONSOLIDATED";
